# Generated by Django 4.2.16 on 2026-04-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('disciplina', models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack')], max_length=5)),
                ('frecuencia', models.CharField(choices=[('2x', '2 veces por semana'), ('3x', '3 veces por semana'), ('5x', '5 veces por semana'), ('libre', 'Pase Libre')], max_length=10)),
                ('combo', models.CharField(blank=True, choices=[('', 'Sin combo'), ('hyrox_cf', 'Combo Hyrox + CF'), ('hyrox_hf', 'Combo Hyrox + HF')], default='', max_length=20)),
                ('bonus_pack', models.BooleanField(default=False)),
                ('horario', models.CharField(blank=True, max_length=20)),
                ('tipo_precio', models.CharField(choices=[('regular', 'Regular (1–10)'), ('unlpam', 'UNLPam (1–10)'), ('despues_10', 'Después del día 10')], default='regular', max_length=20)),
                ('cuota_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mora', 'En mora'), ('baja', 'Baja'), ('alejado', 'Alejado'), ('temporal', 'Temporal')], default='activo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
