# Generated by Django 4.2.16 on 2026-06-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_discipconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='horario_combo',
            field=models.CharField(blank=True, help_text='Horario de la disciplina combo (ej: Hyrox). Solo aplica cuando combo != ""', max_length=20),
        ),
    ]
