# Generated by Django 4.2.16 on 2026-07-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_horario_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegocioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Athlon', max_length=100)),
                ('ciudad', models.CharField(blank=True, default='General Pico, La Pampa', max_length=120)),
                ('logo_claro', models.TextField(blank=True, help_text='Logo para fondo oscuro (sistema). Data URI base64.')),
                ('logo_oscuro', models.TextField(blank=True, help_text='Logo para fondo claro (PDFs). Data URI base64.')),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuración del negocio',
            },
        ),
    ]
