# Generated by Django 4.2.16 on 2026-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_negocioconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocioconfig',
            name='nombre_sede1',
            field=models.CharField(default='Athlon 107', max_length=60),
        ),
        migrations.AddField(
            model_name='negocioconfig',
            name='nombre_sede2',
            field=models.CharField(default='Athlon 24', max_length=60),
        ),
    ]
