# Generated by Django 4.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_sede_nombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno estable (ej: 107). No cambiar una vez creado.', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible (ej: Athlon 107)', max_length=60)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sede',
            field=models.CharField(max_length=10),
        ),
    ]
