# Generated by Django 4.2.16 on 2026-07-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_seed_sedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='disciplina_2',
            field=models.CharField(blank=True, choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack'), ('FB', 'FullBody')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='frecuencia_2',
            field=models.CharField(blank=True, choices=[('2x', '2 veces por semana'), ('3x', '3 veces por semana'), ('5x', '5 veces por semana'), ('libre', 'Pase Libre')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='horario_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sede_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
