# Generated by Django 4.2.16 on 2026-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alumno_disciplina_2_alumno_frecuencia_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='beneficio_id',
            field=models.CharField(blank=True, default='', help_text='UUID del QR de beneficios (sistema externo en Google).', max_length=60),
        ),
    ]
