# Generated by Django 4.2.16 on 2026-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes')),
                ('disciplina', models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack')], max_length=5)),
                ('frecuencia', models.CharField(choices=[('2x', '2 veces por semana'), ('3x', '3 veces por semana'), ('5x', '5 veces por semana'), ('libre', 'Pase Libre')], max_length=10)),
                ('tipo', models.CharField(choices=[('regular', 'Regular (1–10)'), ('unlpam', 'UNLPam (1–10)'), ('despues_10', 'Después del día 10')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ['-mes', 'disciplina', 'frecuencia'],
                'unique_together': {('mes', 'disciplina', 'frecuencia', 'tipo')},
            },
        ),
    ]
