# Generated by Django 4.2.16 on 2026-04-27 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cant_20000', models.PositiveIntegerField(default=0)),
                ('cant_10000', models.PositiveIntegerField(default=0)),
                ('cant_5000', models.PositiveIntegerField(default=0)),
                ('cant_2000', models.PositiveIntegerField(default=0)),
                ('cant_1000', models.PositiveIntegerField(default=0)),
                ('cant_500', models.PositiveIntegerField(default=0)),
                ('cant_200', models.PositiveIntegerField(default=0)),
                ('cant_100', models.PositiveIntegerField(default=0)),
                ('cant_50', models.PositiveIntegerField(default=0)),
                ('cant_20', models.PositiveIntegerField(default=0)),
                ('cant_10', models.PositiveIntegerField(default=0)),
                ('total_billetes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de caja',
                'verbose_name_plural': 'Arqueos de caja',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'sede')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Positivo = ingreso, negativo = egreso', max_digits=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.arqueocaja')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
