# Generated by Django 4.2.16 on 2026-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
