# Generated by Django 4.2.16 on 2026-05-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_descripcion_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arqueocaja',
            options={'ordering': ['-fecha', '-fecha_registro'], 'verbose_name': 'Arqueo de caja', 'verbose_name_plural': 'Arqueos de caja'},
        ),
        migrations.AlterUniqueTogether(
            name='arqueocaja',
            unique_together=set(),
        ),
    ]
