# Generated by Django 4.2.16 on 2026-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_remove_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes')),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('concepto', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Gasto extra',
                'verbose_name_plural': 'Gastos extras',
                'ordering': ['mes', 'sede', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes')),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('concepto', models.CharField(choices=[('alquiler', 'Alquiler'), ('limpieza', 'Limpieza'), ('municipal', 'Imp. Municipal'), ('salubridad', 'Salubridad e Higiene'), ('electrico', 'Corpico Eléctrico'), ('internet', 'Corpico Internet'), ('seguro', 'Seguro'), ('mono_deni', 'Monotributo Deni'), ('mono_alvaro', 'Monotributo Álvaro'), ('mono_mario', 'Monotributo Mario'), ('iibb_deni', 'IIBB Deni'), ('iibb_alvaro', 'IIBB Álvaro'), ('iibb_mario', 'IIBB Mario')], max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Gasto fijo',
                'verbose_name_plural': 'Gastos fijos',
                'ordering': ['mes', 'sede', 'concepto', 'fecha'],
            },
        ),
    ]
