# Generated by Django 4.2.16 on 2026-05-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_add_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='queda_en_caja',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que queda en caja para el próximo día', max_digits=12),
        ),
    ]
