# Generated by Django 4.2.16 on 2026-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_add_queda_en_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoextra',
            name='sede',
            field=models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24'), ('general', 'General')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gastofijo',
            name='sede',
            field=models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24'), ('general', 'General')], max_length=10),
        ),
    ]
