# Generated by Django 4.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_alter_gastoextra_sede_alter_gastofijo_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='sede',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='sede',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gastofijo',
            name='sede',
            field=models.CharField(max_length=10),
        ),
    ]
