# Generated by Django 4.2.16 on 2026-04-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes')),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('horas', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_horas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_pase_libre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adicional_teens', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adicional_hyrox', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sueldo_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confirmada', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='profes.profe')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-mes', 'profe__nombre'],
                'unique_together': {('profe', 'mes', 'sede')},
            },
        ),
    ]
