# Generated by Django 4.2.16 on 2026-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_rebuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
