# Generated by Django 4.2.16 on 2026-04-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('disciplina', models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack')], max_length=5)),
                ('tipo', models.CharField(choices=[('clase', 'Clase suelta'), ('semana', 'Semana'), ('quincena', 'Quincena'), ('mes', 'Mes completo')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno temporal',
                'verbose_name_plural': 'Alumnos temporales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
