# Generated by Django 4.2.16 on 2026-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnotemporal',
            name='disciplina',
            field=models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack'), ('FB', 'FullBody')], max_length=5),
        ),
    ]
