# Generated by Django 4.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporales', '0002_alter_alumnotemporal_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnotemporal',
            name='sede',
            field=models.CharField(max_length=10),
        ),
    ]
