# Generated by Django 4.2.16 on 2026-04-27 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('abrimos', models.BooleanField(default=False)),
                ('horarios_especiales', models.TextField(blank=True, help_text='Descripción de horarios si abrimos')),
                ('nota', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HorarioReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Lunes de la semana')),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disciplina', models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack')], max_length=5)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('nota', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('profe_planificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_planificados', to='profes.profe')),
                ('profe_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_reales', to='profes.profe')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modificación de horario',
                'verbose_name_plural': 'Modificaciones de horario',
                'ordering': ['-fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='HorarioMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24')], max_length=10)),
                ('dia', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miércoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sábado')], max_length=5)),
                ('hora', models.TimeField()),
                ('disciplina', models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack')], max_length=5)),
                ('capacidad_max', models.PositiveSmallIntegerField(default=21)),
                ('activo', models.BooleanField(default=True)),
                ('profe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_maestro', to='profes.profe')),
            ],
            options={
                'verbose_name': 'Horario maestro',
                'verbose_name_plural': 'Horarios maestros',
                'ordering': ['sede', 'dia', 'hora'],
                'unique_together': {('sede', 'dia', 'hora', 'disciplina')},
            },
        ),
    ]
