# Generated by Django 4.2.16 on 2026-05-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariomaestro',
            options={'ordering': ['sede', 'dia', 'hora', 'fecha_desde'], 'verbose_name': 'Horario maestro', 'verbose_name_plural': 'Horarios maestros'},
        ),
        migrations.AlterUniqueTogether(
            name='horariomaestro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horariomaestro',
            name='fecha_desde',
            field=models.DateField(default='2000-01-01', help_text='Fecha desde la que esta versión del horario es válida'),
        ),
        migrations.AlterUniqueTogether(
            name='horariomaestro',
            unique_together={('sede', 'dia', 'hora', 'disciplina', 'fecha_desde')},
        ),
    ]
