# Generated by Django 4.2.16 on 2026-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_add_fecha_desde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomaestro',
            name='disciplina',
            field=models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack'), ('FB', 'FullBody')], max_length=5),
        ),
        migrations.AlterField(
            model_name='horarioreal',
            name='disciplina',
            field=models.CharField(choices=[('CF', 'Crossfit'), ('HF', 'Heavy Funcional'), ('HX', 'Hyrox'), ('TN', 'Crossfit Teens'), ('KD', 'Crossfit Kids'), ('BP', 'Bonus Pack'), ('FB', 'FullBody')], max_length=5),
        ),
    ]
