# Generated by Django 4.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_horarioreal_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomaestro',
            name='sede',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='horarioreal',
            name='sede',
            field=models.CharField(max_length=10),
        ),
    ]
