# Generated by Django 4.2.16 on 2026-04-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cuota_vencida', 'Cuota vencida'), ('activo_impago', 'Activo impago'), ('reactivacion_1_3m', 'Reactivación 1–3 meses'), ('reactivacion_3_6m', 'Reactivación 3–6 meses'), ('reactivacion_6m', 'Reactivación +6 meses'), ('bienvenida', 'Bienvenida'), ('vence_pronto', 'Vence pronto'), ('cumpleanios', 'Cumpleaños')], max_length=30)),
                ('variante', models.PositiveSmallIntegerField(default=1, help_text='1 o 2')),
                ('texto', models.TextField(help_text='Usar {nombre}, {dias}, {monto}, {sede}, {disciplina}')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template de mensaje',
                'verbose_name_plural': 'Templates de mensajes',
                'unique_together': {('tipo', 'variante')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cuota_vencida', 'Cuota vencida'), ('activo_impago', 'Activo impago'), ('reactivacion_1_3m', 'Reactivación 1–3 meses'), ('reactivacion_3_6m', 'Reactivación 3–6 meses'), ('reactivacion_6m', 'Reactivación +6 meses'), ('bienvenida', 'Bienvenida'), ('vence_pronto', 'Vence pronto'), ('cumpleanios', 'Cumpleaños')], max_length=30)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=15)),
                ('texto', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='alumnos.alumno')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
