# Generated by Django 4.2.16 on 2026-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('cuota_vencida', 'Cuota vencida'), ('activo_impago', 'Activo impago'), ('reactivacion_1_3m', 'Reactivación 1–3 meses'), ('reactivacion_3_6m', 'Reactivación 3–6 meses'), ('reactivacion_6m', 'Reactivación +6 meses'), ('bienvenida', 'Bienvenida'), ('vence_pronto', 'Vence pronto'), ('cumpleanios', 'Cumpleaños'), ('masivo', 'Masivo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='templatemensaje',
            name='tipo',
            field=models.CharField(choices=[('cuota_vencida', 'Cuota vencida'), ('activo_impago', 'Activo impago'), ('reactivacion_1_3m', 'Reactivación 1–3 meses'), ('reactivacion_3_6m', 'Reactivación 3–6 meses'), ('reactivacion_6m', 'Reactivación +6 meses'), ('bienvenida', 'Bienvenida'), ('vence_pronto', 'Vence pronto'), ('cumpleanios', 'Cumpleaños'), ('masivo', 'Masivo')], max_length=30),
        ),
    ]
