# Generated by Django 4.2.16 on 2026-04-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color, ej: #22d3ee', max_length=7)),
                ('sede', models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24'), ('ambas', 'Ambas sedes')], default='ambas', max_length=10)),
                ('tipo_liquidacion', models.CharField(choices=[('hora', 'Por hora'), ('porcentaje', 'Porcentaje de recaudación'), ('fijo', 'Sueldo fijo')], default='hora', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profe',
                'verbose_name_plural': 'Profes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorHoraProfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para Mario u otros con sueldo fijo', max_digits=12, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje sobre recaudación (ej: 50.00 para Day/Mario)', max_digits=5, null=True)),
                ('profe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_hora', to='profes.profe')),
            ],
            options={
                'verbose_name': 'Valor hora profe',
                'verbose_name_plural': 'Valores hora profes',
                'ordering': ['-mes', 'profe__nombre'],
                'unique_together': {('profe', 'mes')},
            },
        ),
    ]
