# Generated by Django 4.2.16 on 2026-07-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profe',
            name='disciplinas_liquidables',
            field=models.JSONField(blank=True, default=list, help_text='Códigos de disciplina que cuentan como horas para este profe (ej: ["CF","HF"]). Vacío = todas.'),
        ),
        migrations.AddField(
            model_name='valorhoraprofe',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto sobre el que se calcula el porcentaje (carga manual)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='profe',
            name='tipo_liquidacion',
            field=models.CharField(choices=[('hora', 'Por hora'), ('porcentaje', 'Porcentaje de recaudación'), ('fijo', 'Sueldo fijo'), ('mixto', 'Horas + Porcentaje')], default='hora', max_length=15),
        ),
    ]
