# Generated by Django 4.2.16 on 2026-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profes', '0002_profe_disciplinas_liquidables_valorhoraprofe_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profe',
            name='sede',
            field=models.CharField(choices=[('107', 'Athlon 107'), ('24', 'Athlon 24'), ('ambas', 'Ambas sedes'), ('general', 'General')], default='ambas', max_length=10),
        ),
    ]
