# Generated by Django 4.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profes', '0003_alter_profe_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profe',
            name='sede',
            field=models.CharField(default='ambas', max_length=10),
        ),
    ]
