# Generated by Django 4.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_stock_por_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='sede',
            field=models.CharField(max_length=10),
        ),
    ]
