# Generated by Django 4.2.16 on 2026-07-16 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_alter_venta_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('envio', 'Envío'), ('venta', 'Venta'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('origen', models.CharField(blank=True, default='', max_length=10)),
                ('destino', models.CharField(blank=True, default='', max_length=10)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='productos.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
